# Generated by Django 4.0.4 on 2022-04-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('effects', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phoneNum', models.CharField(max_length=255, unique=True)),
                ('userLogin', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('privileges', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('probability', models.FloatField()),
                ('state', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('foreignKeyPhase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='riskManagement.phase')),
                ('foreignKeyType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='riskManagement.risktype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('foreignKeyManager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectManager', to='riskManagement.user')),
                ('foreignKeyManagerRisk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riskManager', to='riskManagement.user')),
                ('members', models.ManyToManyField(related_name='members', to='riskManagement.user')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='foreignKeyProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskManagement.project'),
        ),
        migrations.AddField(
            model_name='phase',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='riskManagement.user'),
        ),
    ]
