# Generated by Django 4.0.4 on 2022-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
