# Generated by Django 4.0.4 on 2022-04-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskManagement', '0002_rename_describtion_risk_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='creator',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='riskManagement.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='datetime_created',
            field=models.DateField(default='2022-04-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='impact',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='probability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='reactions',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='state',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='threat',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='triggers',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
